apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
  - namespace.yaml
  - helmrepo.yaml
  - helmrelease.yaml
  - onepassword-connect.yaml
  - cluster-secret-store.yaml
