apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secrets-operator
  - onepassword-connect
  - cert-manager
  - external-dns
  - cloudnative-pg
  - spicedb-operator
  - cilium-gateway
