apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spicedb
resources:
  - namespace.yaml
  - external-secrets.yaml
  - pg-cluster.yaml
  - spicedb-instance.yaml
  - httproute.yaml
  - network-policy.yaml
