name: Topics Service

on:
  push:
    branches: [main]
    paths:
      - "waddle/services/topics/**"
      - ".github/workflows/service-deploy.yaml"
      - "generators/projen-data-service/**"
  pull_request:
    paths:
      - "waddle/services/topics/**"
      - ".github/workflows/service-deploy.yaml"
      - "generators/projen-data-service/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  deploy:
    uses: ./.github/workflows/service-deploy.yaml
    with:
      service-name: topics
      service-path: waddle/services/topics
      has-write-model: false
    secrets: inherit
