apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cloudflare-external-secret.yaml
  - proxmox-csi-external-secret.yaml
  - grafana-external-secret.yaml
  - spicedb-external-secret.yaml
